### ISSUE TITLE
Is reference to IDeliverable.Bits.RegularExpressions necessary?

### ISSUE THREAD

**Issue by jbuck79** [IDeliverable/IDeliverable.Bits#2]
The project file references this assembly but none of the code in the project seems to use it and I have been unable to figure out if this assembly actually exists. My Orchard dashboard was showing an error about it not being able to find the assembly so I just removed the reference from the project file and everything seems to be working.

If it's not necessary, I'd be happy to submit a pull request to take it out.

**Comment by DaRosenberg** [comment]
Ah I've been wondering about this one myself - just spoke to Sipke about it, he says it's a remnant from the past that can be removed now. A PR would be great!
